name: Signal Server Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false  # Skip submodules to avoid private spam-filter dependency

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install Protocol Buffer Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Clean and compile
      run: |
        mvn clean compile -DskipTests -Dmaven.test.skip=true -Pexclude-spam-filter
      env:
        MAVEN_OPTS: "-Xmx2048m"

    - name: Package application
      run: |
        mvn package -DskipTests -Dmaven.test.skip=true -Pexclude-spam-filter
      env:
        MAVEN_OPTS: "-Xmx2048m"

    - name: Create distribution
      run: |
        mkdir -p dist
        
        # List target directories to debug
        echo "Service target contents:"
        ls -la service/target/ || echo "Service target directory not found"
        echo "WebSocket target contents:"
        ls -la websocket-resources/target/ || echo "WebSocket target directory not found"
        
        # Find and copy service JAR
        SERVICE_JAR=$(find service/target -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -1)
        if [ -n "$SERVICE_JAR" ]; then
          cp "$SERVICE_JAR" dist/signal-server.jar
          echo "Copied service JAR: $SERVICE_JAR"
        else
          echo "Service JAR not found, checking for alternative patterns..."
          find service/target -name "*.jar" -type f || echo "No JAR files found in service/target"
        fi
        
        # Find and copy websocket-resources JAR
        WS_JAR=$(find websocket-resources/target -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -1)
        if [ -n "$WS_JAR" ]; then
          cp "$WS_JAR" dist/websocket-resources.jar
          echo "Copied websocket JAR: $WS_JAR"
        else
          echo "WebSocket JAR not found, checking for alternative patterns..."
          find websocket-resources/target -name "*.jar" -type f || echo "No JAR files found in websocket-resources/target"
        fi
        
        # Copy configuration files
        CONFIG_FILE="service/config/sample.yml"
        if [ -f "$CONFIG_FILE" ]; then
          cp "$CONFIG_FILE" dist/config.yml
          echo "Copied config file: $CONFIG_FILE"
        else
          echo "Config file not found at $CONFIG_FILE, checking alternatives..."
          find service -name "*.yml" -o -name "*.yaml" | head -5
          # Create a basic config template if none found
          cat > dist/config.yml << 'EOFCONFIG'
# Signal Server Configuration
# This is a template configuration file - modify as needed

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Add your DynamoDB and other service configurations here
EOFCONFIG
          echo "Created basic config template"
        fi
        
        # Create startup script
        cat > dist/start-server.sh << 'EOF'
        #!/bin/bash
        echo "Starting Signal Server..."
        java -jar signal-server.jar server config.yml
        EOF
        chmod +x dist/start-server.sh
        
        # Create Windows startup script
        cat > dist/start-server.bat << 'EOF'
        @echo off
        echo Starting Signal Server...
        java -jar signal-server.jar server config.yml
        pause
        EOF
        
        # Create README
        cat > dist/README.md << 'EOF'
        # Signal Server Distribution
        
        ## Files included:
        - `signal-server.jar` - Main server application
        - `websocket-resources.jar` - WebSocket resources
        - `config.yml` - Configuration file (modify as needed)
        - `start-server.sh` - Linux/Mac startup script
        - `start-server.bat` - Windows startup script
        
        ## Quick Start:
        1. Modify `config.yml` with your settings
        2. Run `./start-server.sh` (Linux/Mac) or `start-server.bat` (Windows)
        
        ## Requirements:
        - Java 21 or higher
        - Configured database (DynamoDB)
        - Valid configuration in config.yml
        
        ## Custom Features:
        This build includes CarlJoy's static verification code feature.
        Phone numbers + verification codes are stored as static passwords.
        EOF

    - name: Create version info
      run: |
        echo "Build Date: $(date)" > dist/VERSION.txt
        echo "Git Commit: ${{ github.sha }}" >> dist/VERSION.txt
        echo "Git Branch: ${{ github.ref_name }}" >> dist/VERSION.txt
        echo "Build Number: ${{ github.run_number }}" >> dist/VERSION.txt

    - name: Create ZIP archive
      run: |
        cd dist
        zip -r ../signal-server-build-${{ github.run_number }}.zip .
        cd ..
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: signal-server-build-${{ github.run_number }}
        path: |
          dist/
          signal-server-build-${{ github.run_number }}.zip
        retention-days: 30
      if: always()

    - name: Upload JAR files (if exist)
      uses: actions/upload-artifact@v4
      with:
        name: jar-files-${{ github.run_number }}
        path: |
          service/target/*.jar
          websocket-resources/target/*.jar
        retention-days: 30
      continue-on-error: true
      if: always()

  # 创建Release（仅在推送到main/master分支时）
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: signal-server-build-${{ github.run_number }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: build-${{ github.run_number }}
        release_name: Signal Server Build ${{ github.run_number }}
        body: |
          Automated build of Signal Server
          
          **Changes:**
          - Added static verification code feature (CarlJoy)
          - Phone verification via static passwords instead of SMS
          
          **Build Info:**
          - Commit: ${{ github.sha }}
          - Date: ${{ github.event.head_commit.timestamp }}
          
          **Download:**
          Download the ZIP file below for a complete distribution.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./signal-server-build-${{ github.run_number }}.zip
        asset_name: signal-server-build-${{ github.run_number }}.zip
        asset_content_type: application/zip 