name: Signal Server Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false  # Skip submodules to avoid private spam-filter dependency

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install Protocol Buffer Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

        - name: Build with Maven
      run: |
        mvn install -DskipTests -Pexclude-spam-filter
      env:
        MAVEN_OPTS: "-Xmx2048m"

    - name: Copy JAR files
      run: |
        mkdir -p dist
        cp service/target/*.jar dist/
        ls -la dist/
        
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: signal-server-jar-${{ github.run_number }}
        path: dist/*.jar
        retention-days: 30



  # 创建Release（仅在推送到main/master分支时）
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download JAR artifacts
      uses: actions/download-artifact@v4
      with:
        name: signal-server-jar-${{ github.run_number }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: Signal Server Build ${{ github.run_number }}
        body: |
          Signal Server JAR build with static verification codes feature.
          
          **Build Info:**
          - Commit: ${{ github.sha }}
          - Build: ${{ github.run_number }}
        files: "*.jar"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 